### ISSUE TITLE
creazione server.php

### ISSUE THREAD

**Issue by Borrellsss** [Borrellsss/git-branch-merge#1]
@Alex12012000 crea cortesemente l'array in un file server.php nel quale sarà presente un array di array. Buon lavoro

**Comment by Alex12012000** [comment]
Ciao @Borrellsss ho creato il file server.php ed ora è pronto per la revisione!

**Comment by Borrellsss** [comment]
@Alex12012000 ottimo provvedo immediatamente, grazie ancora! :)

**Comment by Borrellsss** [comment]
@Alex12012000 revisione effettuata. Tutto pronto per il Merge, buon lavoro!

**Comment by Alex12012000** [comment]
Merge effettuato, buon lavoro! :)
