### ISSUE TITLE
coversione dell'array in api in un in file php a parte

### ISSUE THREAD

**Issue by Borrellsss** [Borrellsss/git-branch-merge#2]
@kaijie26 una volta che @Alex12012000  avrà terminato il suo lavoro e avrà effettuato il merge potrai iniziare con la procedura di conversione dell'array da lui creato in file .json così da poter avere a disposizione l'api. A presto.

**Comment by kaijie26** [comment]
@Borrellsss lavoro effettuato, è pronta la revisione grazie mille

**Comment by Borrellsss** [comment]
Revisione effettuata, si può proceder con il Merge. Buon lavoro! :)

**Comment by kaijie26** [comment]
@Borrellsss merge effettuato
