### ISSUE TITLE
chiamata api

### ISSUE THREAD

**Issue by Borrellsss** [Borrellsss/git-branch-merge#3]
@KOVU9529 quando @kaijie26  metterà a disposizione l'api e verrà fatto il merge potrai effettuare una chiamata in un file js utilizzando Vue. Buona giornata.

**Comment by kaijie26** [comment]
@KOVU9529 la conversione in api è effettuata puoi procedere pure

**Comment by KOVU9529** [comment]
@Borrellsss chiamata effettuata in un file js utilizzando Vue, pronto per la revisione, in attesa di notizie ti auguro una buona giornata:)

**Comment by Borrellsss** [comment]
@KOVU9529 revisione effettuata, tutt'ok. Puoi procedere con il Merge. Buona giornata a te :)

**Comment by KOVU9529** [comment]
@Borrellsss Merge effettuato, buon proseguimento.:)
