### ISSUE TITLE
Applicazione stili CSS

### ISSUE THREAD

**Issue by Borrellsss** [Borrellsss/git-branch-merge#5]
@andrea-mangiapia ti occuperai della parte di CSS una volta che il progetto base sarà terminato. Ti aggiornerò quando sarà tutto pronto. Buona giornata.

**Comment by Borrellsss** [comment]
cards stampate in pagina controlla cortesemente che tutto sia ok così da poter effettuare il merge. Grazie

**Comment by andrea-mangiapia** [comment]
@Borrellsss tutto ok, puoi procedere con il merge

**Comment by andrea-mangiapia** [comment]
@Borrellsss Css completato, se è tutto ok procedo con il merge

**Comment by Borrellsss** [comment]
tutto perfetto, procedi con il Merge. Ottimo lavoro!
